remote_theme: just-the-docs/just-the-docs
plugins:
- jekyll-remote-theme
color_scheme: dark
title: Forgotten Games
description: Documentation for how to run old and abandoned games on modern hardware.
url: https://zhiftydk.github.io/ForgottenGames