remote_theme: just-the-docs/just-the-docs
plugins:
- jekyll-remote-theme
title: Forgotten Games Documentation
description: Documentation for the SafeDisc game engine
url: https://zhiftydk.github.io/ForgottenGames